# Generated by Django 3.2.9 on 2022-01-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(choices=[('Zugfestigkeit', 'Tensile Strength'), ('Dehngrenze', 'Breaking Strength'), ('Dichte', 'Density'), ('Bruchdehnung', 'Fracture Strain'), ('Härte', 'Hardness')], max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
