# Generated by Django 3.2.9 on 2022-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20220116_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='depth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
