# Generated by Django 3.2.9 on 2022-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20220129_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
